version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.11.3

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn
      - run: yarn all
